/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    application
}

repositories {
    mavenCentral()
}


dependencies {
    implementation("org.postgresql:postgresql:42.2.23");
}

application {
    mainClass = "com.example.Main"
}

tasks {
    jar {
        manifest {
            attributes["Main-Class"] = "com.example.Main"
        }
        from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    }
}