services:
  database:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: lekito
      POSTGRES_PASSWORD: lekito
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=lekito
      - DB_PASSWORD=lekito
    depends_on:
      database:
        condition: service_healthy
